spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/media_database?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.myself.mybatis.entity



jpa:
  show-sql: true
  hibernate:
    ddl-auto:update

