server:
  port: 8080


spring:
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/seuAllmedia?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver





  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/

  devtools:
    remote:
      restart:
        enabled: true
        additional-paths: src/main/java     #监听目录




mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
  type-aliases-package: com.zph.entity


