spring:
  datasource:
    url: jdbc:mysql://223.3.95.103:3306/media?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: liuzijian
    password: lzj123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mapper/*.xml